### PR TITLE
ECDR-6: Create initial impl of dynamic OSDD.

### PR DESCRIPTION
**Pull request by mrmateo**
[Review on Reviewable](https://reviewable.io/reviews/di2e/ecdr/35)

### CODE REVIEW

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/35)



---

Let me know what you think. A little ugly right now, but it does work :)

---

<sup>**[endpoint/cdr-rest-broker-endpoint/src/main/java/net/di2e/ecdr/broker/endpoint/rest/CDRRestBrokerServiceImpl.java, line 128 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfFxxWvRWOJW2_up2Qu)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/endpoint/cdr-rest-broker-endpoint/src/main/java/net/di2e/ecdr/broker/endpoint/rest/CDRRestBrokerServiceImpl.java#L128)):</sup>
Ugliness #1. Wasn't sure how to specify this as they differ between the two endpoints.

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 164 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfFy0O9mhLft92WyJJ-)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L164)):</sup>
You can access this by going to the endpoint and doing /osd.xml. Example: http://localhost:8181/services/cdr/search/rest/osd.xml

Works for both CDR OS and CDR Broker

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/XMLTemplates.java, line 15 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfFyFiL-SYGV9XacemC)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/XMLTemplates.java#L15)):</sup>
Big ugliness #2. Could not get the osd_info.template file to be readable from the endpoints (I think it's because the Abstract endpoint is trying to read it in, but the abstract endpoint is being pulled in and embedded inside the individual bundles. This is also where we need to update the documentation so that it looks decent and worthwhile.

---

<sup>**[libs/cdr-rest-search-commons/src/main/resources/osd_info.template, line 1 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfFy_5rRGm6SFG9wZBf)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/resources/osd_info.template#L1)):</sup>
Optimally I would like to just have a normal file instead of having it in the class as it looks much cleaner without the string markup. This is just a copy/paste of the DISA one. The one in the java I customized a little bit.

---

<sup>**[libs/cdr-rest-search-commons/src/main/resources/schema/osd.xsd, line 1 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfFyjy_y7bHuxFBcGWd)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/resources/schema/osd.xsd#L1)):</sup>
There were a few Opensearch schemas out there but nothing that looked really solid. I was thinking maybe we could put this (and the JAXB objects) into the cohesive-int area as it's own project that people could use. There was a couple schemas in the DDF code but they are just for testing and didn't have the cdr federation.

---

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/35)

Reviewed files:
- endpoint/cdr-rest-broker-endpoint/pom.xml @ r1
- endpoint/cdr-rest-broker-endpoint/src/main/java/net/di2e/ecdr/broker/endpoint/rest/CDRRestBrokerServiceImpl.java @ r1
- endpoint/cdr-rest-search-endpoint/src/main/java/net/di2e/ecdr/search/endpoint/rest/CDRRestSearchServiceImpl.java @ r1
- federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/AbstractFederationStrategy.java @ r1
- federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/FifoFederationStrategy.java @ r1
- federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/NormalizingSortedFederationStrategy.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/fs/Link.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/fs/ObjectFactory.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/fs/package-info.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/fs/Rel.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/fs/SourceDescription.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/osd/ObjectFactory.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/osd/OpenSearchDescription.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/osd/package-info.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/osd/Query.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/osd/SyndicationRight.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/osd/Url.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/XMLTemplates.java @ r1
- libs/cdr-rest-search-commons/src/main/resources/osd_info.template @ r1
- libs/cdr-rest-search-commons/src/main/resources/schema/fs.xsd @ r1
- libs/cdr-rest-search-commons/src/main/resources/schema/osd.xsd @ r1
- libs/cdr-rest-search-commons/src/main/resources/schema/xjc.txt @ r1
- libs/cdr-rest-search-commons/src/test/java/net/di2e/ecdr/commons/xml/OpenSearchDescriptionTest.java @ r1

---

Looks good!

---

<sup>**[endpoint/cdr-rest-broker-endpoint/src/main/java/net/di2e/ecdr/broker/endpoint/rest/CDRRestBrokerServiceImpl.java, line 128 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfFxxWvRWOJW2_up2Qu)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/endpoint/cdr-rest-broker-endpoint/src/main/java/net/di2e/ecdr/broker/endpoint/rest/CDRRestBrokerServiceImpl.java#L128)):</sup>
We can always make this more dynamic in the long run (like allowing an Admin the ability to specify additional parameters for things like enhanced search), but for now I think hardcoded is more than fine.  I am a big believe of getting something that is stable and works, and then enhancing it to make it more flexible down the line (if needed).

---

<sup>**[endpoint/cdr-rest-broker-endpoint/src/main/java/net/di2e/ecdr/broker/endpoint/rest/CDRRestBrokerServiceImpl.java, line 131 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfPLn8Jb14AbJPslP7m)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/endpoint/cdr-rest-broker-endpoint/src/main/java/net/di2e/ecdr/broker/endpoint/rest/CDRRestBrokerServiceImpl.java#L131)):</sup>
I can go in and ensure the parameters are correct (e.g. we don't have a filter parameter).  

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 207 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfPyno_mIXEvQ8Jyr2W)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L207)):</sup>
This is where the stuff with the comments gets injected right?

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/XMLTemplates.java, line 15 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfFyFiL-SYGV9XacemC)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/XMLTemplates.java#L15)):</sup>
Should we look at not embedding the common jar and expose those classes via export?  Or can we use the OSGI registry (to inject the template)?

---

<sup>**[libs/cdr-rest-search-commons/src/main/resources/osd_info.template, line 1 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfFy_5rRGm6SFG9wZBf)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/resources/osd_info.template#L1)):</sup>
Yeah I think that would be good.  But if it is easier to work with the one in Java initially, do that, then we can figure out the classloading stuff

---

<sup>**[libs/cdr-rest-search-commons/src/main/resources/schema/fs.xsd, line 16 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfPy45o-etIdayXza5v)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/resources/schema/fs.xsd#L16)):</sup>
Did you make this up, or find it from somewhere?  Not a big deal either way, just wondering.

---

<sup>**[libs/cdr-rest-search-commons/src/main/resources/schema/osd.xsd, line 1 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfFyjy_y7bHuxFBcGWd)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/resources/schema/osd.xsd#L1)):</sup>
Yeah I like that idea

---

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/35)







---

<sup>**[endpoint/cdr-rest-broker-endpoint/src/main/java/net/di2e/ecdr/broker/endpoint/rest/CDRRestBrokerServiceImpl.java, line 128 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfFxxWvRWOJW2_up2Qu)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/endpoint/cdr-rest-broker-endpoint/src/main/java/net/di2e/ecdr/broker/endpoint/rest/CDRRestBrokerServiceImpl.java#L128)):</sup>
Yeah, that was my thought too after spending so much time on it.

---

<sup>**[endpoint/cdr-rest-broker-endpoint/src/main/java/net/di2e/ecdr/broker/endpoint/rest/CDRRestBrokerServiceImpl.java, line 131 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfPLn8Jb14AbJPslP7m)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/endpoint/cdr-rest-broker-endpoint/src/main/java/net/di2e/ecdr/broker/endpoint/rest/CDRRestBrokerServiceImpl.java#L131)):</sup>
OK, thanks! 

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 207 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfPyno_mIXEvQ8Jyr2W)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L207)):</sup>
Yep, it's basically just adding it to the top of the file. I didn't find anything specifically built into JAXB for this, most people just did something like this were they would add the text into the writer/string being outputted.

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/XMLTemplates.java, line 15 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfFyFiL-SYGV9XacemC)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/XMLTemplates.java#L15)):</sup>
That's a good idea. I looked briefly at just trying to inject the .template but ran out of time on Friday and pushed what I had.

---

<sup>**[libs/cdr-rest-search-commons/src/main/resources/schema/fs.xsd, line 16 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfPy45o-etIdayXza5v)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/resources/schema/fs.xsd#L16)):</sup>
I made it up from looking at the search spec. The zip you sent me a while back with the specs has some schemas but nothing really complete for an OSDD (just a couple really basic OSDD examples) and no schemas for them.

---

**Comment by mrmateo** [comment]
@jvettraino - just pushed a new change that uses the .template file instead of the private class

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/35)

Reviewed files:
- endpoint/cdr-rest-broker-endpoint/pom.xml @ r2
- endpoint/cdr-rest-search-endpoint/pom.xml @ r2
- libs/cdr-rest-search-commons/pom.xml @ r2
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java @ r2
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/xml/XMLTemplates.java @ r2
- libs/cdr-rest-search-commons/src/main/resources/osd_info.template @ r2
- libs/cdr-rest-search-commons/src/main/resources/schema/fs.xsd @ r1
- libs/cdr-rest-search-commons/src/main/resources/templates/osd_info.template @ r2

---

Looks good!  Take a look at including the "real" values of the sort order if you get a chance into the comments.  Then then there are also some defaults in the Endpoint settings that we may want to include, so glance at that (or just let me know if you want me to update it as well).

I am good if you want to merge this stuff now, then we can continue to iterate on it (with the items mentioned above)

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 207 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfPyno_mIXEvQ8Jyr2W)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L207)):</sup>
Gotcha, so one thing we can explore doing is putting some place holder strings in the String template, and then replacing them with up-to-date values.  For example the sort orders that are supported we can replace in there (I am not sure if there are any other ones, will have to think about it)

---

<sup>**[libs/cdr-rest-search-commons/src/main/resources/schema/fs.xsd, line 16 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfPy45o-etIdayXza5v)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/resources/schema/fs.xsd#L16)):</sup>
Gotcha, looks good!

---

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/35)



---

OK. I think I will merge it in then so that it's all in there (and I won't have to worry about merge issues with other code).

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 207 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/35#-JfPyno_mIXEvQ8Jyr2W)** ([raw file](https://github.com/di2e/ecdr/blob/55f13148e2f2e75d204bc0e6ac2cc6d75d62609f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L207)):</sup>
That's a good suggestion. I'll make a new ticket for that.

---

**Pull request merged**
