### PR TITLE
ECDR-69 Added support for the fuzzy parameter for keyword queries and al...

### PR DESCRIPTION
**Pull request by jvettraino**
...so for defaulting the fuzzy parameter.

[Review on Reviewable](https://reviewable.io/reviews/di2e/ecdr/30)

### CODE REVIEW

**Comment by jvettraino** [comment]
FYI @mrmateo

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/30)

Reviewed files:
- endpoint/cdr-rest-broker-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml @ r1
- endpoint/cdr-rest-search-endpoint/src/main/resources/OSGI-INF/blueprint/service-blueprint.xml @ r1
- endpoint/cdr-rest-search-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/constants/SearchConstants.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/CDRQueryImpl.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/TextualCriteria.java @ r1
- libs/cdr-rest-search-commons/src/test/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParserTest.java @ r1





---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/CDRQueryImpl.java, line 179 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/30#-JeiDRGGIo69zjoKPRs4)** ([raw file](https://github.com/di2e/ecdr/blob/aa0f321c4037663ce9d01a19bfae6fd39e3f2386/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/CDRQueryImpl.java#L179)):</sup>
Need to add textualCriteria.isFuzzy()

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java, line 56 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/30#-JeiE3UPzy6w0HW4PjIY)** ([raw file](https://github.com/di2e/ecdr/blob/aa0f321c4037663ce9d01a19bfae6fd39e3f2386/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java#L56)):</sup>
SZIE should be SIZE

---

**Comment by mrmateo** [comment]
Looks pretty good to me other than the couple comments I added.

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/30)







---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/CDRQueryImpl.java, line 179 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/30#-JeiDRGGIo69zjoKPRs4)** ([raw file](https://github.com/di2e/ecdr/blob/aa0f321c4037663ce9d01a19bfae6fd39e3f2386/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/CDRQueryImpl.java#L179)):</sup>
Done.

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java, line 56 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/30#-JeiE3UPzy6w0HW4PjIY)** ([raw file](https://github.com/di2e/ecdr/blob/aa0f321c4037663ce9d01a19bfae6fd39e3f2386/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java#L56)):</sup>
Done.

---

**Comment by jvettraino** [comment]
Thanks @mrmateo I updated the 2 files and will merge now.

**Comment by blackbelt080** [comment]
Is the params passed in non null call creating a single entry point only for keywords that are in TextualCriteria? I.e are there multiple endpoints for search strings who keywords are more broad in logic with and / or mutual exclusive e.g TextualCriteria and textualCriteria /TextualCriteria or TextualCriteria
Let me know if you need further clarification

**Comment by jvettraino** [comment]
@blackbelt080 I am not sure I am following your question. Can you reference a class and a method or line of code? Thanks!

**Pull request merged**
