### PR TITLE
ECDR-45: Added security logic to sources.

### PR DESCRIPTION
**Pull request by mrmateo**
[Review on Reviewable](https://reviewable.io/reviews/di2e/ecdr/37)

### CODE REVIEW

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/37)







---

<sup>**[source/cdr-rest-source/pom.xml, line 160 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/37#-Jfik9huWSQUzliU48O-)** ([raw file](https://github.com/di2e/ecdr/blob/f31fcedf22e9471248102f08eb7a1b6e6b87e1f2/source/cdr-rest-source/pom.xml#L160)):</sup>
Tried to think a little outside the box here. Instead of copy/pasting the code I was able to 'embed' the spatial logic code that performs the security-adding. Looking to do consolidate this code into the security-api bundle as right now it's already duplicated in ddf-catalog and ddf-spatial. I'll make a ticket for that soon (but will probably not work it until after our release is done).

---

<sup>**[source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java, line 528 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/37#-JfikBhjQ3UwGl26XrrK)** ([raw file](https://github.com/di2e/ecdr/blob/f31fcedf22e9471248102f08eb7a1b6e6b87e1f2/source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java#L528)):</sup>
This should do what you were asking for in the comments.

---

**Comment by mrmateo** [comment]
@jvettraino - initial commit. still doing a little testing but it looks good so far.

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/37)

Reviewed files:
- source/cdr-rest-source/pom.xml @ r1
- source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java @ r1
- source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/SecuritySource.java @ r1
- source/cdr-rest-source/src/main/resources/OSGI-INF/metatype/cdr-metatype.xml @ r1
- source/cdr-rest-source/src/main/resources/OSGI-INF/metatype/opensearch-metatype.xml @ r2

---

As always, looks really good.  A of comment about config options I just thought of.

---

<sup>**[source/cdr-rest-source/pom.xml, line 62 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/37#-JflmsdS4yuAoQz79dg8)** ([raw file](https://github.com/di2e/ecdr/blob/f31fcedf22e9471248102f08eb7a1b6e6b87e1f2/source/cdr-rest-source/pom.xml#L62)):</sup>
Should we move this version to a property?

---

<sup>**[source/cdr-rest-source/pom.xml, line 160 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/37#-Jfik9huWSQUzliU48O-)** ([raw file](https://github.com/di2e/ecdr/blob/f31fcedf22e9471248102f08eb7a1b6e6b87e1f2/source/cdr-rest-source/pom.xml#L160)):</sup>
Nice, I like it!

---

<sup>**[source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java, line 177 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/37#-JflnujeTuImQ2kPOMgT)** ([raw file](https://github.com/di2e/ecdr/blob/f31fcedf22e9471248102f08eb7a1b6e6b87e1f2/source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java#L177)):</sup>
Can we make this configurable as well via the Config Admin for each of the Sources.  Basically a checkbox that allows you to check to propogate the credentials in a SAML Cookie.  Thinking we should have it checked by default in the CDR Source and unchecked in the OpenSearch Source

On a completely separate note - I think we talked about whether or not Java will send the cookie if connecting over HTTP and it will, I tested it out the other day.  Perhaps in that checkbox config up above we should mention that it should only be used when connecting to HTTPS sources.

Thoughts?

---

<sup>**[source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java, line 528 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/37#-JfikBhjQ3UwGl26XrrK)** ([raw file](https://github.com/di2e/ecdr/blob/f31fcedf22e9471248102f08eb7a1b6e6b87e1f2/source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java#L528)):</sup>
It would be nice to have some sort of security helper function to do this as well (if you move stuff into DDF)

---

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/37)







---

<sup>**[source/cdr-rest-source/pom.xml, line 62 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/37#-JflmsdS4yuAoQz79dg8)** ([raw file](https://github.com/di2e/ecdr/blob/f31fcedf22e9471248102f08eb7a1b6e6b87e1f2/source/cdr-rest-source/pom.xml#L62)):</sup>
Good point. I'll add that in. I was hoping this would be 'temporary' :)

---

<sup>**[source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java, line 177 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/37#-JflnujeTuImQ2kPOMgT)** ([raw file](https://github.com/di2e/ecdr/blob/f31fcedf22e9471248102f08eb7a1b6e6b87e1f2/source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java#L177)):</sup>
Yeah, I can add that in. In that case, it wouldn't necessarily only be HTTPS and it should work (with a security-enabled DDF/DIB) for either HTTP or HTTPS, right?

---

<sup>**[source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java, line 528 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/37#-JfikBhjQ3UwGl26XrrK)** ([raw file](https://github.com/di2e/ecdr/blob/f31fcedf22e9471248102f08eb7a1b6e6b87e1f2/source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java#L528)):</sup>
Agreed. Could easily have a service that just returns a TLSClientParameters and underneath the scenes gets the keystores and sets these properties.

---

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/37)







---

<sup>**[source/cdr-rest-source/pom.xml, line 62 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/37#-JflmsdS4yuAoQz79dg8)** ([raw file](https://github.com/di2e/ecdr/blob/f31fcedf22e9471248102f08eb7a1b6e6b87e1f2/source/cdr-rest-source/pom.xml#L62)):</sup>
Yeah I was thinking temporary too, which is why I commented as a question.  Probably moving it makes sense so we remember easier.

---

<sup>**[source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java, line 177 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/37#-JflnujeTuImQ2kPOMgT)** ([raw file](https://github.com/di2e/ecdr/blob/f31fcedf22e9471248102f08eb7a1b6e6b87e1f2/source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java#L177)):</sup>
Correct it would technically work over HTTP/HTTPS, but should probably only be used for HTTPS sources for production.

---

**Comment by mrmateo** [comment]
OK @jvettraino , I think I got everything from your comments.

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/37)

Reviewed files:
- pom.xml @ r3
- source/cdr-rest-source/pom.xml @ r3
- source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java @ r3
- source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/CDRRestSource.java @ r3
- source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/OpenSearchSource.java @ r3
- source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/SecuritySource.java @ r1
- source/cdr-rest-source/src/main/resources/OSGI-INF/metatype/cdr-metatype.xml @ r3
- source/cdr-rest-source/src/main/resources/OSGI-INF/metatype/opensearch-metatype.xml @ r3

---

Looks good!!!  Merge when ready

---

**Pull request merged**
