### PR TITLE
ECDR-67: Added functionality to make sort value customizable.

### PR DESCRIPTION
**Pull request by mrmateo**
Also fixed some spelling errors and slf4j'ified some log messages.

[Review on Reviewable](https://reviewable.io/reviews/di2e/ecdr/34)

### CODE REVIEW

**Comment by mrmateo** [comment]
@jvettraino - I'm still working on updating the sources but wanted to let you get eyes-on this now so I can make changes. I will update this PR and tag you when I push the source updates.

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/34)







---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 106 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf4HkGjULKcfHkGtzOj)** ([raw file](https://github.com/di2e/ecdr/blob/aed4f6f0d5432d09bc4191d3fe0093f2492f6f60/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L106)):</sup>
Instead of using the id from the metacard, they're each assigned a random UUID. This fixes the runtimeexception of adding two items with the same key. The UUID is only used in here, it does not replace the id in the metacard.

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 141 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf4Hyk77A5WdeGjTo5_)** ([raw file](https://github.com/di2e/ecdr/blob/aed4f6f0d5432d09bc4191d3fe0093f2492f6f60/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L141)):</sup>
Changed to exception to cover runtimeexceptions

---

<sup>**[source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java, line 481 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf4HXvg3AQmrPXXfS1d)** ([raw file](https://github.com/di2e/ecdr/blob/aed4f6f0d5432d09bc4191d3fe0093f2492f6f60/source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java#L481)):</sup>
This error message confused for for about 10 minutes while I was debugging stuff so I decided to clarify it a little more.

---

**Comment by mrmateo** [comment]
OK @jvettraino , just added in the code for support with the sources. Should be good for full review.

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/34)







---

<sup>**[endpoint/cdr-rest-broker-endpoint/src/main/resources/OSGI-INF/blueprint/service-blueprint.xml, line 87 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf6DaP4pu5zpjQKVotC)** ([raw file](https://github.com/di2e/ecdr/blob/39747e78e0f6cb7cec604c05b3fc4d9ab3da8b25/endpoint/cdr-rest-broker-endpoint/src/main/resources/OSGI-INF/blueprint/service-blueprint.xml#L87)):</sup>
Do you mean since they are already defined in the BasicQueryParser class? If so, I agree. They are not needed.

---

<sup>**[federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/DefaultSortTypeConfigurations.java, line 28 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf6LSyAzPdxx4jsIcGt)** ([raw file](https://github.com/di2e/ecdr/blob/39747e78e0f6cb7cec604c05b3fc4d9ab3da8b25/federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/DefaultSortTypeConfigurations.java#L28)):</sup>
This installs the initial default sort mappings.

---

<sup>**[federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/DefaultSortTypeConfigurations.java, line 40 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf6GV2w_pqtUODFOUPD)** ([raw file](https://github.com/di2e/ecdr/blob/39747e78e0f6cb7cec604c05b3fc4d9ab3da8b25/federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/DefaultSortTypeConfigurations.java#L40)):</sup>
No reason not to. Just changed them over to use that.

---

<sup>**[federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/SortTypeConfigurationImpl.java, line 13 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf6HFuo1ikW6ZZ_4o_9)** ([raw file](https://github.com/di2e/ecdr/blob/39747e78e0f6cb7cec604c05b3fc4d9ab3da8b25/federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/SortTypeConfigurationImpl.java#L13)):</sup>
Yeah, it might not be the best place. I originally added it here as I though the strategy would be using it the most (but I was wrong about that). The endpoints just use the API interface so it wouldn't make sense to put the impl in their bundles. I thought about putting it inside of cdr-rest-search-common, but there is no place that could be used to run a blueprint / metatype since that bundle is embedded by many other bundles. 

So I was thinking it would either be to make it out into its own bundle (with just this impl and the default class) or to add it to an existing bundle that starts services.

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 141 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf4Hyk77A5WdeGjTo5_)** ([raw file](https://github.com/di2e/ecdr/blob/aed4f6f0d5432d09bc4191d3fe0093f2492f6f60/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L141)):</sup>
For clarification, you've been doing the catch on 'RuntimeException'? I did 'Exception' to catch the non-RuntimeExceptions that are thrown by the code and any extra runtimeexceptions. I could explicitly have it catch on both.

---

<sup>**[source/cdr-rest-source/src/main/resources/OSGI-INF/metatype/cdr-metatype.xml, line 50 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf6KHkcTqvJlF0YhgXI)** ([raw file](https://github.com/di2e/ecdr/blob/39747e78e0f6cb7cec604c05b3fc4d9ab3da8b25/source/cdr-rest-source/src/main/resources/OSGI-INF/metatype/cdr-metatype.xml#L50)):</sup>
ok

---

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/34)







---

<sup>**[endpoint/cdr-rest-broker-endpoint/src/main/resources/OSGI-INF/blueprint/service-blueprint.xml, line 87 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf6DaP4pu5zpjQKVotC)** ([raw file](https://github.com/di2e/ecdr/blob/39747e78e0f6cb7cec604c05b3fc4d9ab3da8b25/endpoint/cdr-rest-broker-endpoint/src/main/resources/OSGI-INF/blueprint/service-blueprint.xml#L87)):</sup>
Exactly

---

<sup>**[federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/DefaultSortTypeConfigurations.java, line 28 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf6LSyAzPdxx4jsIcGt)** ([raw file](https://github.com/di2e/ecdr/blob/39747e78e0f6cb7cec604c05b3fc4d9ab3da8b25/federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/DefaultSortTypeConfigurations.java#L28)):</sup>
Okay so this is the out of the box default mappings that get used unless anything else is configured (or removed?) via the metatype right?  Can these be removed from the metatype if they are not supported -  don't have a real use case for that, but just wanted to check so I understand.

---

<sup>**[federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/SortTypeConfigurationImpl.java, line 13 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf6HFuo1ikW6ZZ_4o_9)** ([raw file](https://github.com/di2e/ecdr/blob/39747e78e0f6cb7cec604c05b3fc4d9ab3da8b25/federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/SortTypeConfigurationImpl.java#L13)):</sup>
Yeah maybe  a separate bundle is best

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 141 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf4Hyk77A5WdeGjTo5_)** ([raw file](https://github.com/di2e/ecdr/blob/aed4f6f0d5432d09bc4191d3fe0093f2492f6f60/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L141)):</sup>
Yeah for cleanliness (what Fortify told me :) ), 

---

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/34)







---

<sup>**[endpoint/cdr-rest-broker-endpoint/src/main/resources/OSGI-INF/blueprint/service-blueprint.xml, line 87 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf6DaP4pu5zpjQKVotC)** ([raw file](https://github.com/di2e/ecdr/blob/39747e78e0f6cb7cec604c05b3fc4d9ab3da8b25/endpoint/cdr-rest-broker-endpoint/src/main/resources/OSGI-INF/blueprint/service-blueprint.xml#L87)):</sup>
OK, I'll take them out.

---

<sup>**[federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/DefaultSortTypeConfigurations.java, line 28 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf6LSyAzPdxx4jsIcGt)** ([raw file](https://github.com/di2e/ecdr/blob/39747e78e0f6cb7cec604c05b3fc4d9ab3da8b25/federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/DefaultSortTypeConfigurations.java#L28)):</sup>
They can be removed from the webconsole, yes.

---

<sup>**[federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/SortTypeConfigurationImpl.java, line 13 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf6HFuo1ikW6ZZ_4o_9)** ([raw file](https://github.com/di2e/ecdr/blob/39747e78e0f6cb7cec604c05b3fc4d9ab3da8b25/federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/SortTypeConfigurationImpl.java#L13)):</sup>
OK, will do.

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 141 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf4Hyk77A5WdeGjTo5_)** ([raw file](https://github.com/di2e/ecdr/blob/aed4f6f0d5432d09bc4191d3fe0093f2492f6f60/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L141)):</sup>
OK. Updated it using the cleaner java 7 way of handling multiple exceptions (we don't need to support java 6, do we?).

---

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/34)







---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 141 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-Jf4Hyk77A5WdeGjTo5_)** ([raw file](https://github.com/di2e/ecdr/blob/aed4f6f0d5432d09bc4191d3fe0093f2492f6f60/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L141)):</sup>
No java 7 is all good

---

**Comment by mrmateo** [comment]
@jvettraino - just pushed a new set of changes to address your comments.

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/34)

Reviewed files:
- apps/cdr-app/src/main/resources/features.xml @ r3
- endpoint/cdr-endpoint-sortmapper/pom.xml @ r3
- endpoint/cdr-endpoint-sortmapper/src/main/java/net/di2e/ecdr/endpoint/sort/DefaultSortTypeConfigurations.java @ r3
- endpoint/cdr-endpoint-sortmapper/src/main/java/net/di2e/ecdr/endpoint/sort/SortTypeConfigurationImpl.java @ r3
- endpoint/cdr-endpoint-sortmapper/src/main/resources/META-INF/spring/beans.xml @ r3
- endpoint/cdr-endpoint-sortmapper/src/main/resources/OSGI-INF/metatype/metatype.xml @ r3
- endpoint/cdr-rest-broker-endpoint/src/main/resources/OSGI-INF/blueprint/service-blueprint.xml @ r3
- endpoint/pom.xml @ r3
- federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/DefaultSortTypeConfigurations.java @ r3
- federation/cdr-federation-strategies/src/main/java/net/di2e/ecdr/federation/SortTypeConfigurationImpl.java @ r3
- federation/cdr-federation-strategies/src/main/resources/META-INF/spring/beans.xml @ r3
- federation/cdr-federation-strategies/src/main/resources/OSGI-INF/blueprint/blueprint.xml @ r3
- federation/cdr-federation-strategies/src/main/resources/OSGI-INF/metatype/metatype.xml @ r3
- libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java @ r3
- source/cdr-rest-source/src/main/resources/OSGI-INF/metatype/cdr-metatype.xml @ r3
- source/cdr-rest-source/src/main/resources/OSGI-INF/metatype/opensearch-metatype.xml @ r3

---

Nice, I like it!

---

<sup>**[endpoint/cdr-endpoint-sortmapper/src/main/resources/OSGI-INF/metatype/metatype.xml, line 23 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-JfA5YUoqJ8yfilUZtBi)** ([raw file](https://github.com/di2e/ecdr/blob/8f2e9fe1a6001d98e22945d1f5c098b826ef0277/endpoint/cdr-endpoint-sortmapper/src/main/resources/OSGI-INF/metatype/metatype.xml#L23)):</sup>
We would want a way to do a custom mapping as well (For things that may be inside the DDMS).  Understood that those values would have to exist as custom metacard attributes.

Should we add an optional text field that they could configure with that info?  So it would be like an XOR between the dropdown and the textfield

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 143 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-JfA6COmHk9Jb_Pveitb)** ([raw file](https://github.com/di2e/ecdr/blob/8f2e9fe1a6001d98e22945d1f5c098b826ef0277/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L143)):</sup>
Nice!  Yeah doing stuff like this keeps Fortify and tools like that a little happier, and with the Java 7 stuff it actually doesn't clog up the code.

---

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/34)







---

<sup>**[endpoint/cdr-endpoint-sortmapper/src/main/resources/OSGI-INF/metatype/metatype.xml, line 23 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/34#-JfA5YUoqJ8yfilUZtBi)** ([raw file](https://github.com/di2e/ecdr/blob/8f2e9fe1a6001d98e22945d1f5c098b826ef0277/endpoint/cdr-endpoint-sortmapper/src/main/resources/OSGI-INF/metatype/metatype.xml#L23)):</sup>
Yeah that makes sense. I'll add that this afternoon and will tag you. 

---

**Comment by mrmateo** [comment]
@jvettraino  - just pushed the new update

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/34)

Reviewed files:
- endpoint/cdr-endpoint-sortmapper/pom.xml @ r4
- endpoint/cdr-endpoint-sortmapper/src/main/java/net/di2e/ecdr/endpoint/sort/SortTypeConfigurationImpl.java @ r4
- endpoint/cdr-endpoint-sortmapper/src/main/resources/OSGI-INF/metatype/metatype.xml @ r4

---

Looks great!  Merge when ready

---

**Pull request merged**
