### PR TITLE
ECDR-131: Update to add fuzzy to each word.

### PR DESCRIPTION
**Pull request by mrmateo**
This prevents fuzzy from being added to the entire phrase, which is invalid for lucene.

@jvettraino

[Review on Reviewable](https://reviewable.io/reviews/di2e/ecdr/67)

### CODE REVIEW

**Comment by jvettraino** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 179 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/67#-JrxU8fvYPFXfP1lkcV_)** ([raw file](https://github.com/di2e/ecdr/blob/892a50cb31320746c43c0a1c2f8bbf178020741c/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L179)):</sup>
Do we need to account for how we handle Booleans?  Meaning do we need to parse out the AND, OR NOT booleans?  If so how does that change from CQL to the CDR Keyword Query Language?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/67)

**Comment by mrmateo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 179 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/67#-JrxU8fvYPFXfP1lkcV_)** ([raw file](https://github.com/di2e/ecdr/blob/892a50cb31320746c43c0a1c2f8bbf178020741c/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L179)):</sup>
that's a good point, ill put in a check for any OPERATORS and not fuzzy on them. really this should only work for the keyword query language (since we're re-indexing based on keywords). That said, I am thinking this should be skipped for CQL-based queries...thoughts? 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/67)

**Comment by jvettraino** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 65 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/67#-JrxZyqBb3tzoctdqKGb)** ([raw file](https://github.com/di2e/ecdr/blob/892a50cb31320746c43c0a1c2f8bbf178020741c/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L65)):</sup>
Is this value right?  Its different from what gets sent in the endpoint which is 'source'?

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 67 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/67#-JrxZnOc-FjdCZB3n9e1)** ([raw file](https://github.com/di2e/ecdr/blob/892a50cb31320746c43c0a1c2f8bbf178020741c/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L67)):</sup>
These constants you should be able to get from SearchConstants.

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 179 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/67#-JrxU8fvYPFXfP1lkcV_)** ([raw file](https://github.com/di2e/ecdr/blob/892a50cb31320746c43c0a1c2f8bbf178020741c/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L179)):</sup>
Okay great!  Yeah I think that would make sense at least right now (keeping it simple) to skip CQL support.  Can you add support for that or create a ticket for it (whatever you want).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/67)

**Comment by mrmateo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 65 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/67#-JrxZyqBb3tzoctdqKGb)** ([raw file](https://github.com/di2e/ecdr/blob/892a50cb31320746c43c0a1c2f8bbf178020741c/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L65)):</sup>
looks like that wasn't being used. I think it was from an earlier time when we were only normalizing if it was a federated query

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 67 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/67#-JrxZnOc-FjdCZB3n9e1)** ([raw file](https://github.com/di2e/ecdr/blob/892a50cb31320746c43c0a1c2f8bbf178020741c/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L67)):</sup>
ok, updating.

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 179 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/67#-JrxU8fvYPFXfP1lkcV_)** ([raw file](https://github.com/di2e/ecdr/blob/892a50cb31320746c43c0a1c2f8bbf178020741c/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L179)):</sup>
Created ECDR-133 for adding in CQL support.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/67)

**Comment by jvettraino** [comment]
Okay looks good, feel free to merge, once you make the final updates

**Comment by mrmateo** [comment]
@jvettraino can you look at this updated commit?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/67)

**Comment by mrmateo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 179 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/67#-JrxwG-ShVRMfhyHzyNH)** ([raw file](https://github.com/di2e/ecdr/blob/03c2131812106047a3648418d027c04c7bae44f2/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L179)):</sup>
probably don't need the 'contains' here as the get will just return null if the parameter isn't there. StringUtils should handle the null input OK. ill fix that before the merge

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/67)

**Comment by jvettraino** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 172 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/67#-JrxyC8ZXRgk4O2bhamP)** ([raw file](https://github.com/di2e/ecdr/blob/03c2131812106047a3648418d027c04c7bae44f2/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L172)):</sup>
Should this class also check the query language to make sure it is not CQL?

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 217 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/67#-JrxxoMwAaqw_LLspwFR)** ([raw file](https://github.com/di2e/ecdr/blob/03c2131812106047a3648418d027c04c7bae44f2/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L217)):</sup>
I am going to look into if we actually need the '50000.00' passed in, but don't let it hold up your PR, if we don't I will update as part of the cleanup ticket.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/67)

**Comment by mrmateo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 172 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/67#-JrxyC8ZXRgk4O2bhamP)** ([raw file](https://github.com/di2e/ecdr/blob/03c2131812106047a3648418d027c04c7bae44f2/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L172)):</sup>
Ah yep. Thanks. That was the reason I made this method in the first place. I'll update it; apparently I'm rusty :)

---

<sup>**[libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java, line 217 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/67#-JrxxoMwAaqw_LLspwFR)** ([raw file](https://github.com/di2e/ecdr/blob/03c2131812106047a3648418d027c04c7bae44f2/libs/cdr-libs-result-relevance-normalizer/src/main/java/net/di2e/ecdr/libs/result/relevance/RelevanceNormalizer.java#L217)):</sup>
Hmm yeah. I forgot what it is for.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/67)

**Comment by mrmateo** [comment]
@jvettraino if you could give this last update a quick look. I had to update the CDRQueryImpl code to return a reference to the query parameters. Not sure if you know of a better way.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/67)

**Pull request merged**
