### PR TITLE
ECDR-85: Added parameter pass-through to source.

### PR DESCRIPTION
**Pull request by mrmateo**
[Review on Reviewable](https://reviewable.io/reviews/di2e/ecdr/36)

### CODE REVIEW

**Comment by mrmateo** [comment]
@jvettraino - initial updates for ECDR-85 support of parameter passing.

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/36)

Reviewed files:
- endpoint/cdr-rest-broker-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml @ r1
- endpoint/cdr-rest-search-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/PropertyCriteria.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java @ r1
- source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java @ r1
- source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/CDRRestSource.java @ r1
- source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/OpenSearchSource.java @ r1
- source/cdr-rest-source/src/main/resources/OSGI-INF/metatype/cdr-metatype.xml @ r1
- source/cdr-rest-source/src/main/resources/OSGI-INF/metatype/opensearch-metatype.xml @ r1
- source/cdr-rest-source/src/test/java/net/di2e/ecdr/source/rest/CDROpenSearchSourceTest.java @ r1





---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java, line 362 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/36#-JfazKfaM493S-2x87hO)** ([raw file](https://github.com/di2e/ecdr/blob/8e7bd6a1746938cc769c92758c4240275d46d7d2/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java#L362)):</sup>
This begs the question of if we should really be taking in a HTTP Parameter to DDF value pair in the parameterExtension list.  For example we would have uid:id which would mean the uid HTTP parameter should get mapped to the DDF internal value of ID.

Likewise going out the source it would be just the opposite (so similar to what we do for sort order).

What do you think?  If you agree you can add it to this (if you think it's easy, or we can push it off down the road).  Adding it provides us extreme flexibility.

*** Update after reviewing the Source files, it looks like you already ahead of me :) and did that mapping on the source so I think it 100% makes sense to add it in the end point if it is not too tough (you could even default it to behave as it does now if only a single value is entered in, but then also support name=value - do whatever you think is best)***

---

<sup>**[source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/OpenSearchSource.java, line 91 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/36#-Jfb-9fN_D166zys1AHB)** ([raw file](https://github.com/di2e/ecdr/blob/590a5eccbfe04068d7010790642073a3fffa23fd/source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/OpenSearchSource.java#L91)):</sup>
Nice clean up!

---

<sup>**[source/cdr-rest-source/src/main/resources/OSGI-INF/metatype/opensearch-metatype.xml, line 75 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/36#-Jfb-QsU6MbkbctP5qag)** ([raw file](https://github.com/di2e/ecdr/blob/8e7bd6a1746938cc769c92758c4240275d46d7d2/source/cdr-rest-source/src/main/resources/OSGI-INF/metatype/opensearch-metatype.xml#L75)):</sup>
Nice

---

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/36)







---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java, line 362 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/36#-JfazKfaM493S-2x87hO)** ([raw file](https://github.com/di2e/ecdr/blob/8e7bd6a1746938cc769c92758c4240275d46d7d2/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java#L362)):</sup>
Yeah I think that is definitely do-able. Do you think it would make sense to do it like the sources where the brokered source was 'defaulted' while the search source had all of the configurations available?

---

**Comment by mrmateo** [comment]
@jvettraino - just added in support for ECDR-84, with defaults for the non-criteria parameters of oid and path.

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/36)

Reviewed files:
- endpoint/cdr-rest-broker-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml @ r2
- endpoint/cdr-rest-search-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml @ r2
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java @ r2
- source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java @ r2

---

Awesome!

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java, line 362 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/36#-JfazKfaM493S-2x87hO)** ([raw file](https://github.com/di2e/ecdr/blob/8e7bd6a1746938cc769c92758c4240275d46d7d2/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java#L362)):</sup>
Yeah I like that!

---

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/36)

Reviewed files:
- endpoint/cdr-rest-broker-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml @ r3
- endpoint/cdr-rest-search-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml @ r3
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java @ r3
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/util/SearchUtils.java @ r3
- libs/cdr-rest-search-commons/src/test/java/net/di2e/ecdr/commons/util/SearchUtilsTest.java @ r3
- source/cdr-rest-source/src/main/java/net/di2e/ecdr/source/rest/AbstractCDRSource.java @ r3
- source/cdr-rest-source/src/main/resources/OSGI-INF/metatype/cdr-metatype.xml @ r3

---

Looks good.  After you merge it, I will mess around with it and let you know hoe it goes.

---

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/36)



---

OK. Yeah that's probably the best way to check this stuff out as it deals a lot with the metatypes that are hard to visualize from code. I'll merge this in but will keep the tickets in review until after you've had some time to check it out.

---

**Pull request merged**
