### PR TITLE
ECDR-93: Added configuration to dynamically configure feed security.

### PR DESCRIPTION
**Pull request by mrmateo**
FYI @jvettraino 

[Review on Reviewable](https://reviewable.io/reviews/di2e/ecdr/46)

### CODE REVIEW

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/46)

Reviewed files:
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AtomTransformer.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AtomTransformerWithPayload.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/FeedSecurityConfiguration.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/ConfigurationSecurityMarkingHandler.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/DefaultAtomFeedConfig.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/FeedSecurityConfigurationImpl.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/SecurityConfiguration.java @ r1
- transformer/cdr-atom-result-xformer/src/main/resources/META-INF/spring/beans.xml @ r1
- transformer/cdr-atom-result-xformer/src/main/resources/OSGI-INF/blueprint/atom-blueprint.xml @ r1
- transformer/cdr-atom-result-xformer/src/main/resources/OSGI-INF/metatype/metatype.xml @ r1
- transformer/cdr-atom-result-xformer/src/test/java/net/di2e/ecdr/search/transform/atom/response/AtomTransformerTest.java @ r1





---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java, line 121 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/46#-JkFHPvPkjjXqLdNzjel)** ([raw file](https://github.com/di2e/ecdr/blob/50fbda075295059b392d5820fec378388d89f876/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java#L121)):</sup>
Ahh I remember now that the Default Security Markings (that were identified for the Feed), were also used as a fallback option for the Metadata.  I think we still need an option, but perhaps it should be different than the  feed.  Thoughts on how to do that?  We could have a separate config for that, or maybe it could be a specific type (default-metacard) for the service factory stuff (although that is kind of hacky it seems - mixing meanings).

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/DefaultAtomFeedConfig.java, line 42 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/46#-JkFOZF5M5MEaUQ5OMVZ)** ([raw file](https://github.com/di2e/ecdr/blob/58409bfa37a119f343992b3b421c39a0af29fa9e/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/DefaultAtomFeedConfig.java#L42)):</sup>
The other out of the box format we support is atom-ddms, so we should add that in there as well (and default to the same markings as atom-dds-4.1)

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/resources/OSGI-INF/metatype/metatype.xml, line 27 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/46#-JkFQaKJTEq8pYOyRBOB)** ([raw file](https://github.com/di2e/ecdr/blob/58409bfa37a119f343992b3b421c39a0af29fa9e/transformer/cdr-atom-result-xformer/src/main/resources/OSGI-INF/metatype/metatype.xml#L27)):</sup>
I am confused on whey there is a format and a feedSecurityFormat (and they are the same thing).  What am I missing?

The feed format should be dynamically chosen based on the user input on if they requested atom-ddms-4.1, atom-ddms, or atom-ddms-2.0 - by what is specified in the opensearch format parameter that is passed in.  I can't tell if that is what is happening or if this is the 'hardcoded' global setting

---

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/46)







---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java, line 121 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/46#-JkFHPvPkjjXqLdNzjel)** ([raw file](https://github.com/di2e/ecdr/blob/50fbda075295059b392d5820fec378388d89f876/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java#L121)):</sup>
I guess that would be like what I have now, they could specific a fallback format that would be used in the atom transformer configuration.

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/DefaultAtomFeedConfig.java, line 42 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/46#-JkFOZF5M5MEaUQ5OMVZ)** ([raw file](https://github.com/di2e/ecdr/blob/58409bfa37a119f343992b3b421c39a0af29fa9e/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/DefaultAtomFeedConfig.java#L42)):</sup>
ok

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/resources/OSGI-INF/metatype/metatype.xml, line 27 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/46#-JkFQaKJTEq8pYOyRBOB)** ([raw file](https://github.com/di2e/ecdr/blob/58409bfa37a119f343992b3b421c39a0af29fa9e/transformer/cdr-atom-result-xformer/src/main/resources/OSGI-INF/metatype/metatype.xml#L27)):</sup>
Ah ok, yeah they would be the same thing then. I'll take it out of the atom transformer settings.

---

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/46)

Reviewed files:
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java @ r2
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AtomTransformer.java @ r2
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AtomTransformerWithPayload.java @ r2
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/FeedSecurityConfiguration.java @ r2
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/ConfigurationSecurityMarkingHandler.java @ r2
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/DefaultAtomFeedConfig.java @ r2
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/FeedSecurityConfigurationImpl.java @ r2
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/SecurityConfigurationImpl.java @ r2
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/SecurityConfiguration.java @ r2
- transformer/cdr-atom-result-xformer/src/main/resources/META-INF/spring/beans.xml @ r2
- transformer/cdr-atom-result-xformer/src/main/resources/OSGI-INF/blueprint/atom-blueprint.xml @ r2
- transformer/cdr-atom-result-xformer/src/main/resources/OSGI-INF/metatype/metatype.xml @ r2
- transformer/cdr-atom-result-xformer/src/test/java/net/di2e/ecdr/search/transform/atom/response/AtomTransformerTest.java @ r2

---

Looks good! If you merge I will do some testing. 

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java, line 122 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/46#-JkK0xMpv5ZXYB023oAr)** ([raw file](https://github.com/di2e/ecdr/blob/b936c734cbcb4610c6b99ea319a41b23cdd0ca1c/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java#L122)):</sup>
Nice! 

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java, line 159 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/46#-JkK19lYkZ2JVBn4_EOB)** ([raw file](https://github.com/di2e/ecdr/blob/b936c734cbcb4610c6b99ea319a41b23cdd0ca1c/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java#L159)):</sup>
Can we add an 'else' log message here.  This should ideally never happen as we always want to set security  (or at least blank it out in config)

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/DefaultAtomFeedConfig.java, line 43 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/46#-JkK2PogQRThIjl2Wy8b)** ([raw file](https://github.com/di2e/ecdr/blob/b936c734cbcb4610c6b99ea319a41b23cdd0ca1c/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/DefaultAtomFeedConfig.java#L43)):</sup>
Nice!

---

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/46)







---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java, line 159 \[r2\]](https://reviewable.io:443/reviews/di2e/ecdr/46#-JkK19lYkZ2JVBn4_EOB)** ([raw file](https://github.com/di2e/ecdr/blob/b936c734cbcb4610c6b99ea319a41b23cdd0ca1c/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java#L159)):</sup>
Good call, i just updated that so that it would use the fallback. I had originally planned on doing that but forgot to add it.

---

**Pull request merged**
