### PR TITLE
ECDR-120 updated to break apart the query languages into their own bundles

### PR DESCRIPTION
**Pull request by jvettraino**
This is the initial pull request.  I updated the unit tests, and ran the CDR CTK.  Still doing some more updates and testing.  

For now I left the logic to cycle through the query languages as a list, because it is not expected that there will be that many (there are only 2 right now), will update to make that more efficient shortly.

@mrmateo

[Review on Reviewable](https://reviewable.io/reviews/di2e/ecdr/64)

### CODE REVIEW

**Comment by mrmateo** [comment]
Review status: 17 of 63 files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- api/cdr-api-auditor/pom.xml @ r1
- api/cdr-api-auditor/src/main/java/net/di2e/ecdr/api/auditor/SearchAuditor.java @ r1
- api/cdr-api/pom.xml @ r1
- api/cdr-api/src/main/java/net/di2e/ecdr/api/auditor/SearchAuditor.java @ r1
- api/cdr-api/src/main/java/net/di2e/ecdr/api/query/QueryConfiguration.java @ r1
- api/cdr-api/src/main/java/net/di2e/ecdr/api/query/QueryCriteria.java @ r1
- api/cdr-api/src/main/java/net/di2e/ecdr/api/query/QueryLanguage.java @ r1
- api/pom.xml @ r1
- apps/cdr-app/src/main/resources/features.xml @ r1
- endpoint/cdr-rest-broker-endpoint/src/main/java/net/di2e/ecdr/broker/endpoint/rest/CDRRestBrokerServiceImpl.java @ r1
- endpoint/cdr-rest-broker-endpoint/src/main/resources/OSGI-INF/blueprint/service-blueprint.xml @ r1
- endpoint/cdr-rest-broker-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml @ r1
- endpoint/cdr-rest-search-endpoint/src/main/java/net/di2e/ecdr/search/endpoint/rest/CDRRestSearchServiceImpl.java @ r1
- endpoint/cdr-rest-search-endpoint/src/main/resources/OSGI-INF/blueprint/service-blueprint.xml @ r1
- endpoint/cdr-rest-search-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml @ r1
- libs/cdr-rest-search-commons/pom.xml @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/constants/BrokerConstants.java @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/64)

**Comment by mrmateo** [comment]
Review status: all files reviewed, 6 unresolved discussions, all commit checks successful.
Reviewed files:
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/constants/SearchConstants.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/CDRQueryCriteriaImpl.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/CDRQueryImpl.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/GeospatialCriteria.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/PropertyCriteria.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/QueryConfigurationImpl.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/CDRQueryImpl.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParser.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/BrokerQueryParser.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/LegacyQueryParser.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/rest/parsers/QueryParser.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/TemporalCriteria.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/TextualCriteria.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/util/GeospatialHelper.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/util/keywordparser/ASTNode.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/util/keywordparser/KeywordASTNode.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/util/keywordparser/KeywordTextParser.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/util/keywordparser/OperatorASTNode.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/util/keywordparser/PhraseDelimiterASTNode.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/util/SearchUtils.java @ r1
- libs/cdr-rest-search-commons/src/test/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestEndpointTest.java @ r1
- libs/cdr-rest-search-commons/src/test/java/net/di2e/ecdr/commons/query/rest/CDRQueryImplCQLTest.java @ r1
- libs/cdr-rest-search-commons/src/test/java/net/di2e/ecdr/commons/query/rest/parsers/BasicQueryParserTest.java @ r1
- libs/cdr-rest-search-commons/src/test/java/net/di2e/ecdr/commons/util/SearchUtilsTest.java @ r1
- pom.xml @ r1
- querylanguages/cdr-cql-querylanguage/pom.xml @ r1
- querylanguages/cdr-cql-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/cql/CQLQueryLanguage.java @ r1
- querylanguages/cdr-cql-querylanguage/src/main/resources/OSGI-INF/blueprint/blueprint.xml @ r1
- querylanguages/cdr-cql-querylanguage/src/test/java/net/di2e/ecdr/querylanguage/cql/CDRQueryImplCQLTest.java @ r1
- querylanguages/cdr-keyword-querylanguage/pom.xml @ r1
- querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/CDRKeywordQueryLanguage.java @ r1
- querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/GeospatialCriteria.java @ r1
- querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/keywordparser/ASTNode.java @ r1
- querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/keywordparser/KeywordASTNode.java @ r1
- querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/keywordparser/KeywordTextParser.java @ r1
- querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/keywordparser/OperatorASTNode.java @ r1
- querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/keywordparser/PhraseDelimiterASTNode.java @ r1
- querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/PropertyCriteria.java @ r1
- querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/TemporalCriteria.java @ r1
- querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/TextualCriteria.java @ r1
- querylanguages/cdr-keyword-querylanguage/src/main/resources/OSGI-INF/blueprint/blueprint.xml @ r1
- querylanguages/cdr-keyword-querylanguage/src/test/java/net/di2e/ecdr/querylanguage/basic/CDRKeywordQueryLanguageTest.java @ r1
- querylanguages/pom.xml @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java @ r1
- transformer/cdr-atom-result-xformer/src/test/java/net/di2e/ecdr/search/transform/atom/response/AtomTransformerTest.java @ r1

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/CDRQueryImpl.java, line 2 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/64#-JrcZe9cCFuo-_BWFiOV)** ([raw file](https://github.com/di2e/ecdr/blob/2b6a53e4890882fbb578c0e43dbf6742fa8cbd1f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/CDRQueryImpl.java#L2)):</sup>
The maven license plugin didn't pick this up? We should probably re-run it do change all of the licenses.

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/CDRQueryImpl.java, line 137 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/64#-Jrc_4BptKjN9CbwRmaG)** ([raw file](https://github.com/di2e/ecdr/blob/2b6a53e4890882fbb578c0e43dbf6742fa8cbd1f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/CDRQueryImpl.java#L137)):</sup>
This class is created new for every query, right? Just wanted to make sure we wouldn't have any threading issues with this (since it's sharing a list across the class).

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/QueryConfigurationImpl.java, line 24 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/64#-Jrc_bQAkos7SrMf_7_t)** ([raw file](https://github.com/di2e/ecdr/blob/2b6a53e4890882fbb578c0e43dbf6742fa8cbd1f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/QueryConfigurationImpl.java#L24)):</sup>
Not a big deal, but extra ;

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/util/GeospatialHelper.java, line 33 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/64#-Jrca03i_hlMemtX1Gt3)** ([raw file](https://github.com/di2e/ecdr/blob/2b6a53e4890882fbb578c0e43dbf6742fa8cbd1f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/util/GeospatialHelper.java#L33)):</sup>
Another 'not a big deal' issue, can use StringUtils which allows better null handling and can trim out more than just whitespaces: https://commons.apache.org/proper/commons-lang/javadocs/api-2.6/org/apache/commons/lang/StringUtils.html#trimToEmpty(java.lang.String)

---

<sup>**[querylanguages/cdr-keyword-querylanguage/pom.xml, line 100 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/64#-JrcacFHqkvOvF3Oggqe)** ([raw file](https://github.com/di2e/ecdr/blob/2b6a53e4890882fbb578c0e43dbf6742fa8cbd1f/querylanguages/cdr-keyword-querylanguage/pom.xml#L100)):</sup>
I think this line was only if we were using source files that were LGPL. I didn't see any in your commits though.

---

<sup>**[querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/CDRKeywordQueryLanguage.java, line 65 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/64#-JrcawGcPiixKmSi-yBo)** ([raw file](https://github.com/di2e/ecdr/blob/2b6a53e4890882fbb578c0e43dbf6742fa8cbd1f/querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/CDRKeywordQueryLanguage.java#L65)):</sup>
Was this moved from a different file or did you make it all new?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/64)

**Comment by jvettraino** [comment]
Review status: all files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/CDRQueryImpl.java, line 2 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/64#-JrcZe9cCFuo-_BWFiOV)** ([raw file](https://github.com/di2e/ecdr/blob/2b6a53e4890882fbb578c0e43dbf6742fa8cbd1f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/CDRQueryImpl.java#L2)):</sup>
Yeah I think we need to tune the plugin, I created ECDR-130 for fine tuning the license plugin (so we note the files that shouldn't be checked), and then fix the remaining files that haven't been updated.

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/CDRQueryImpl.java, line 137 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/64#-Jrc_4BptKjN9CbwRmaG)** ([raw file](https://github.com/di2e/ecdr/blob/2b6a53e4890882fbb578c0e43dbf6742fa8cbd1f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/CDRQueryImpl.java#L137)):</sup>
Yeah QueryImpl is created on each new request, so I think we should be okay

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/util/GeospatialHelper.java, line 33 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/64#-Jrca03i_hlMemtX1Gt3)** ([raw file](https://github.com/di2e/ecdr/blob/2b6a53e4890882fbb578c0e43dbf6742fa8cbd1f/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/util/GeospatialHelper.java#L33)):</sup>
Thanks for the pointer, updated. I also moved this class to the net.di2e.ecdr.commons.util package so we only have one util package.  Not sure why there were 2 in the first place.

---

<sup>**[querylanguages/cdr-keyword-querylanguage/pom.xml, line 100 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/64#-JrcacFHqkvOvF3Oggqe)** ([raw file](https://github.com/di2e/ecdr/blob/2b6a53e4890882fbb578c0e43dbf6742fa8cbd1f/querylanguages/cdr-keyword-querylanguage/pom.xml#L100)):</sup>
The code I moved in from the net.di2e.ecdr.querylanguage.basic.keywordparser package which does the keyword syntax parsing is taken from codice, so that is LGPL.  So we need this, but I will make it more fine grained, so it only excludes those files as part of ECDR-130.

---

<sup>**[querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/CDRKeywordQueryLanguage.java, line 65 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/64#-JrcawGcPiixKmSi-yBo)** ([raw file](https://github.com/di2e/ecdr/blob/2b6a53e4890882fbb578c0e43dbf6742fa8cbd1f/querylanguages/cdr-keyword-querylanguage/src/main/java/net/di2e/ecdr/querylanguage/basic/CDRKeywordQueryLanguage.java#L65)):</sup>
This was all pretty much copy paste and re-arranging.  So the QueryLanguage interface and implementation classes are new, but the logic was taken from other areas (like the *Parser classes we used to have but got rid of in favor of these).

As part of doing it, I pulled out the CQL/ECQL logic and moved it into it;s own class, again pretty much copy paste with teh exception of adding in new objects or whatever (no new real logic)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/64)

**Comment by mrmateo** [comment]
Looks good to me!

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/64)

**Comment by mrmateo** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks broke.
Reviewed files:
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/QueryConfigurationImpl.java @ r2
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/util/GeospatialHelper.java @ r2
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/query/util/QueryHelper.java @ r2
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/util/GeospatialHelper.java @ r2
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/util/SearchUtils.java @ r2
- libs/cdr-rest-search-commons/src/test/java/net/di2e/ecdr/commons/query/util/GeospatialHelperTest.java @ r2
- libs/cdr-rest-search-commons/src/test/java/net/di2e/ecdr/commons/util/GeospatialHelperTest.java @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/64)

**Pull request merged**
