### PR TITLE
Add optional locName query capabilities

### PR DESCRIPTION
**Pull request by mrmateo**
Added the location name translation leveraging the new (since ddf 2.7/2.8) geocoder service that is exposed via OSGi.

[Review on Reviewable](https://reviewable.io/reviews/di2e/ecdr/93)

### CODE REVIEW

**Comment by mrmateo** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[apps/cdr-app/pom.xml, line 31 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K29Zqnu3FoBVcqLCnyw)** ([raw file](https://github.com/di2e/ecdr/blob/52d1b1d819344d677d8c7cd7ff0d7cc3ecefa288/apps/cdr-app/pom.xml#L31)):</sup>
Changed this so that it will stop creating a .jar next to the .kar


---

<sup>**[apps/cdr-app/src/main/resources/features.xml, line 85 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K29ZwVmwkbFQ9MIcwmH)** ([raw file](https://github.com/di2e/ecdr/blob/52d1b1d819344d677d8c7cd7ff0d7cc3ecefa288/apps/cdr-app/src/main/resources/features.xml#L85)):</sup>
switched around the order, was having an issue on older (<2.7) DDF versions that would not deploy this feature due to commons not being done before the rest of them.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/93)

**Comment by mrmateo** [comment]
fyi @jvettraino

**Comment by jvettraino** [comment]
Reviewed 1 of 6 files at r1, 2 of 3 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[apps/cdr-app/pom.xml, line 31 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K29Zqnu3FoBVcqLCnyw)** ([raw file](https://github.com/di2e/ecdr/blob/52d1b1d819344d677d8c7cd7ff0d7cc3ecefa288/apps/cdr-app/pom.xml#L31)):</sup>
nice!


---

<sup>**[apps/cdr-app/src/main/resources/features.xml, line 85 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K29ZwVmwkbFQ9MIcwmH)** ([raw file](https://github.com/di2e/ecdr/blob/52d1b1d819344d677d8c7cd7ff0d7cc3ecefa288/apps/cdr-app/src/main/resources/features.xml#L85)):</sup>
Hmm doesn't commons use stuff in the API though?  Did you try the order going API, Commons, Libs Cache?


---

<sup>**[libs/cdr-rest-search-commons/pom.xml, line 105 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K2Adw4IbXVNFhHXl_N8)** ([raw file](https://github.com/di2e/ecdr/blob/52d1b1d819344d677d8c7cd7ff0d7cc3ecefa288/libs/cdr-rest-search-commons/pom.xml#L105)):</sup>
Should we put this version (and the filter proxy) as a property?


---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 92 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K2Ae_aNkfJjH9K4e1eJ)** ([raw file](https://github.com/di2e/ecdr/blob/52d1b1d819344d677d8c7cd7ff0d7cc3ecefa288/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L92)):</sup>
Can you add a comment here, about why we are using List<Object> instead of the List<GeoCoder> (so just a blurb about being compatible with older DDFs and once we don't need to do so, then we can update to be List<GeoCoder>


---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 144 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K2AetNDtdCWiWiIKT5f)** ([raw file](https://github.com/di2e/ecdr/blob/52d1b1d819344d677d8c7cd7ff0d7cc3ecefa288/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L144)):</sup>
Looks good!  


---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 166 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K2Ag7KgEj4CadUvYT37)** ([raw file](https://github.com/di2e/ecdr/blob/52d1b1d819344d677d8c7cd7ff0d7cc3ecefa288/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L166)):</sup>
In here we need to add a default Radius (using the RADIUS parameter) or use the GEOMETRY parameter and pass in a point.  I could go either way on which one we use, any thoughts on if one is better than the other?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/93)

**Comment by mrmateo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[libs/cdr-rest-search-commons/pom.xml, line 105 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K2Adw4IbXVNFhHXl_N8)** ([raw file](https://github.com/di2e/ecdr/blob/52d1b1d819344d677d8c7cd7ff0d7cc3ecefa288/libs/cdr-rest-search-commons/pom.xml#L105)):</sup>
yeah we can. i'll make that change.


---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 92 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K2Ae_aNkfJjH9K4e1eJ)** ([raw file](https://github.com/di2e/ecdr/blob/52d1b1d819344d677d8c7cd7ff0d7cc3ecefa288/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L92)):</sup>
yep, added a comment


---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 166 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K2Ag7KgEj4CadUvYT37)** ([raw file](https://github.com/di2e/ecdr/blob/52d1b1d819344d677d8c7cd7ff0d7cc3ecefa288/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L166)):</sup>
I'm thinking GEOMETRY might be better as that would leverage the geometry parsing code...but we could just add in the default radius which would be pretty simple..hmm. I'll see what looks best.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/93)

**Comment by mrmateo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[apps/cdr-app/src/main/resources/features.xml, line 85 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K29ZwVmwkbFQ9MIcwmH)** ([raw file](https://github.com/di2e/ecdr/blob/52d1b1d819344d677d8c7cd7ff0d7cc3ecefa288/apps/cdr-app/src/main/resources/features.xml#L85)):</sup>
I did not try that, I will change the order to that and see if it still works.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/93)

**Comment by jvettraino** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 166 \[r3\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K2Ag7KgEj4CadUvYT37)** ([raw file](https://github.com/di2e/ecdr/blob/52d1b1d819344d677d8c7cd7ff0d7cc3ecefa288/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L166)):</sup>
Yeah I was leaning towards Geometry as well.  Lets go that route. then we can send it over as a point, and if sources/catalogs want to add a default radius to the point they can do so.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/93)

**Comment by mrmateo** [comment]
@jvettraino  - just pushed some updates to your comments. I believe all of your comments are covered by this commit.


---

Review status: 8 of 11 files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/93)

**Comment by jvettraino** [comment]
Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 172 \[r4\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K2ERJ6EGN7N-bUR1LkK)** ([raw file](https://github.com/di2e/ecdr/blob/83ad09bd93d5b77413855d137c18593149db7c6d/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L172)):</sup>
I was thinking we a nice method to do this, but I couldn't find it.  I assume you came up with the same result.  Perhaps we just roll this into the https://github.com/di2e/ecdr/blob/master/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/util/GeospatialUtils.java class


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/93)

**Comment by mrmateo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 172 \[r4\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K2ERJ6EGN7N-bUR1LkK)** ([raw file](https://github.com/di2e/ecdr/blob/83ad09bd93d5b77413855d137c18593149db7c6d/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L172)):</sup>
Yeah I spent about 30ish minutes looking through the geotools codebase to see if they had anything that did this. I only found a 'WKTWriter' class for JTS...so might be worth it to just convert this to a JTS point and then we could do a .toText() call on it which outputs WKT. Thoughts?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/93)

**Comment by jvettraino** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 172 \[r4\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K2ERJ6EGN7N-bUR1LkK)** ([raw file](https://github.com/di2e/ecdr/blob/83ad09bd93d5b77413855d137c18593149db7c6d/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L172)):</sup>
Yeah that sounds like a good way to go (a little more expensive, but less maintenance.  And lets move the code into the GeoUtil class.  


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/93)

**Comment by mrmateo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java, line 172 \[r4\]](https://reviewable.io:443/reviews/di2e/ecdr/93#-K2ERJ6EGN7N-bUR1LkK)** ([raw file](https://github.com/di2e/ecdr/blob/83ad09bd93d5b77413855d137c18593149db7c6d/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/endpoint/rest/AbstractRestSearchEndpoint.java#L172)):</sup>
ok, will do. i'll ping you once i've merged the code into this PR


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/93)

**Pull request merged**
