### PR TITLE
ECDR-9 Initial commit for getting atom security markings populated 

### PR DESCRIPTION
**Pull request by jvettraino**
This should populate the atom feed with markings that are specified in the config, and it should populate each atom entry with results from the metadata.

[Review on Reviewable](https://reviewable.io/reviews/di2e/ecdr/41)

### CODE REVIEW

**Comment by jvettraino** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/41)



---

Matt - this works but it is still very ugly.  I tried to comment on things I am planning to do if time permits before the 1.0 release, so add comments where you see fit, and definitely let me know if there are critical things I missed.  The only major updates I have as critical are:
 * For the Metadata (atom Entry) security markings, add a SecurityMarkingHandler that uses the config values (like the Atom feed does).  This way it, that will be the last resort option, if it can't find it in the metacard, or in the metadata.
 * Add in logging

So let me know if you see something else as critical.

Thanks

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/constants/SearchConstants.java, line 77 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX6ps_OY9nhfi6XuDl)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/constants/SearchConstants.java#L77)):</sup>
Ignore this, just re-arranged.

---

<sup>**[libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/constants/SecurityConstants.java, line 22 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX6tBaUvEjQKblsHe5)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/constants/SecurityConstants.java#L22)):</sup>
Using the Metacard attribute that was already defined.  Need to run tests to see if this will cause a problem (since we populate with ALL the security markings - and I think they only populate with whatever ones are configured).

---

<sup>**[transformer/cdr-atom-result-xformer/pom.xml, line 94 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX7Ep3HFmgQ6pJ5l-h)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/pom.xml#L94)):</sup>
No idea why I had to do this.  Basically if I don't include this, it doesn't include these files in the bundle, and this packages are local to the bundle.  Thoughts?  This might have been what Doug (MACE) was running into in his email

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java, line 115 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX7SR-r3GCa4hkbqt6)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java#L115)):</sup>
Planning (if time permits) to make dynamic.  Need to ensure sort order, so that may take a little longer to get right.  I know you pointed me to some examples so will check those out.

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java, line 597 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX7ha6iOX-nzfL3tl7)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java#L597)):</sup>
Take a close look at these methods and let me know if you see any gotchas.

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/constants/SecurityConstants.java, line 24 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX7q1SUk7la6u3ObSu)** ([raw file](https://github.com/di2e/ecdr/blob/566d5e4cfa26945f3d5e598011bfec7a83728e41/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/constants/SecurityConstants.java#L24)):</sup>
Ignore this, this was from an intermediate checkin

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/response/security/SecurityMarkingParser.java, line 39 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX8CjlQU8iPCjzvK91)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/response/security/SecurityMarkingParser.java#L39)):</sup>
I need to make this dynamic via config

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/response/security/SecurityMarkingParser.java, line 71 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX86HGpr-q_9u88ufv)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/response/security/SecurityMarkingParser.java#L71)):</sup>
I will remove this method, it is not used.  We always just use the config value for the Feed Security Marking

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/XmlMetadataSecurityMarkingHandler.java, line 33 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX8Zgw0x-nJww1NMbj)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/XmlMetadataSecurityMarkingHandler.java#L33)):</sup>
Check this class, XML parsing is always a little tricky

---

**Comment by jvettraino** [comment]
FYI @mrmateo 
Whenever you get  a chance.

**Comment by mrmateo** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/41)

Reviewed files:
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/constants/SearchConstants.java @ r1
- libs/cdr-rest-search-commons/src/main/java/net/di2e/ecdr/commons/constants/SecurityConstants.java @ r1
- transformer/cdr-atom-result-xformer/pom.xml @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/constants/SecurityConstants.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/response/AtomResponseTransformer.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/response/security/SecurityMarkingParser.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/MetacardSecurityMarkingHandler.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/XmlMetadataSecurityMarkingHandler.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/SecurityConfiguration.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/SecurityData.java @ r1
- transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/SecurityMarkingHandler.java @ r1
- transformer/cdr-atom-result-xformer/src/main/resources/OSGI-INF/blueprint/atom-blueprint.xml @ r1
- transformer/cdr-atom-result-xformer/src/main/resources/OSGI-INF/metatype/metatype.xml @ r1





---

<sup>**[transformer/cdr-atom-result-xformer/pom.xml, line 94 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX7Ep3HFmgQ6pJ5l-h)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/pom.xml#L94)):</sup>
Yeah, I think what I have seen is that when you use Private Package you need to include the local packages (as I guess by default private-package is anything that is local?)

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java, line 115 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX7SR-r3GCa4hkbqt6)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java#L115)):</sup>
Yeah, there's a service sort order that I believe is used in the catalogframework. You can use the service reference comparator here: https://github.com/codice/ddf-catalog/blob/master/core/catalog-core-api-impl/src/main/java/ddf/catalog/util/impl/ServiceComparator.java

Is that what you were thinking of?

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java, line 597 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX7ha6iOX-nzfL3tl7)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/AbstractAtomTransformer.java#L597)):</sup>
I think they look pretty good. Nothing obvious that looks incorrect in the logic.

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/response/security/SecurityMarkingParser.java, line 39 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX8CjlQU8iPCjzvK91)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/response/security/SecurityMarkingParser.java#L39)):</sup>
+1

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/response/security/SecurityMarkingParser.java, line 71 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX86HGpr-q_9u88ufv)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/response/security/SecurityMarkingParser.java#L71)):</sup>
OK, I was actually wondering about that.

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/response/security/SecurityMarkingParser.java, line 96 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgY_KGTuA4ljLMBdf9u)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/response/security/SecurityMarkingParser.java#L96)):</sup>
You'll also remove this method? Looks like it's only used by the above one.

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/XmlMetadataSecurityMarkingHandler.java, line 33 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgX8Zgw0x-nJww1NMbj)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/XmlMetadataSecurityMarkingHandler.java#L33)):</sup>
Best thing to do would probably to have a unit test where you can just add in some example xml files and verify it works.

---

<sup>**[transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/XmlMetadataSecurityMarkingHandler.java, line 55 \[r1\]](https://reviewable.io:443/reviews/di2e/ecdr/41#-JgYhZ7h2bTMrpkUXtvd)** ([raw file](https://github.com/di2e/ecdr/blob/c8d1ed00dc015c6f71610c8b251faf7eb0cb40e4/transformer/cdr-atom-result-xformer/src/main/java/net/di2e/ecdr/search/transform/atom/security/impl/XmlMetadataSecurityMarkingHandler.java#L55)):</sup>
Could security properties potentially get overwritten based on the oder that they come in? IE if there are multiple security elements with similar attributions the last one read would be what the SecurityData would contain.

---

**Comment by jvettraino** [comment]
Committing to get latest changes to @mrmateo to test

**Pull request merged**
