### PR TITLE
ECDR-116 - updated the dependencies of to be looser for CXF (include …

### PR DESCRIPTION
**Pull request by jvettraino**
…2.7 - 4) and also for Joda Time.  Then reworked how the Auditor is referenced in the features file.  Tested against DDF 2.7.x and it worked.

FYI @mrmateo - I did some verification tests against DDF 2.7.x and it seemed to work.  Need to test the security capabilities still, but basica searching worked.

[Review on Reviewable](https://reviewable.io/reviews/di2e/ecdr/55)

### CODE REVIEW

**Comment by mrmateo** [comment]
looks good

---

Reviewed files:
- apps/cdr-app/src/main/resources/features.xml @ r1
- endpoint/cdr-rest-broker-endpoint/pom.xml @ r1
- endpoint/cdr-rest-describe-endpoint/pom.xml @ r1
- endpoint/cdr-rest-search-endpoint/pom.xml @ r1
- libs/cdr-rest-search-commons/pom.xml @ r1
- pom.xml @ r1
- source/cdr-rest-source/pom.xml @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/di2e/ecdr/55)

**Comment by jvettraino** [comment]
Kind of scares me :)

I am going to do a quick look at the imports of each bundle when it is running on DDF just to make sure I didn't miss any optional things or anything like that.  If it looks good, I will merge.

Very happy we don't have to branch our code!

**Comment by mrmateo** [comment]
so this should also work on the 2.6.x and 2.5.x versions of ddf?

**Comment by jvettraino** [comment]
Yup

**Pull request merged**
